#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Maypole-Component
version:      0.01
version_from: Component.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
